name: Run cleanup utility
on:
  workflow_dispatch:
  schedule:
    - cron: "00 0,2,4,8,10,12,14,16,18,20,22 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Build and run
      env:
        UTIL_TOKEN: ${{ secrets.UTIL_TOKEN }}
      run: dotnet run KirillAldashkin/ping $UTIL_TOKEN
      working-directory: RunsCleanUtility
